### PR TITLE
Smc monitor

### PR DESCRIPTION
**Pull request by kevinchern**
## What?
1. ​Add options in `AdaptiveJarzynski.java` to support "full scan" MCMC moves, as well as option to record weights.
2. Refactor some code in `SCM.java`, e.g., encapsulate code for recording statistics into a method.
3. Ouptut an estimate of the relative variance of Z-hat (log space)
4. Add option to control root solver's absolute accuracy in `AdaptiveTemperatureSchedule.java` 
5. Add SMC genealogy plot in `DefaultPostProcessor.xtend`

## Why?
1. Provides more control over algorithm details; optional outputting of weights can be useful for, for example, computing expectations without final rejuvenation steps, which can be more accurate than with rejuvenation steps.
2. It started to look messy after I added a couple more statistics to output.
3. The estimate is nearly cost-free, shouldn't hurt to output.
4. Useful for controlling degree of accuracy, which may impact computation speed.
5. Useful for diagnostics.

## Additional comments
- Point 5 introduced additional requirements from R libraries: `cowplot` and `tidyverse`. `Tidyverse` might be a bit excessive, but `cowplot` benefits SMC diagnostic plots: side-by-side plots with shared axes can be more insightful.
- Requires https://github.com/UBC-Stat-ML/bayonet/pull/34
- Package dependencies in `build.gradle` are not updated; build project manually in Eclipse using the `bayonet` version above.

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
There is a new version of bayonet now, 4.1.12, including your changes. Do you want to updated that PR with that version, then we can merge it.

**Comment by kevinchern** [comment]
> There is a new version of bayonet now, 4.1.12, including your changes. Do you want to updated that PR with that version, then we can merge it.

Updated and also added a fix for handling edge case in plotting (when forward sampling).

**Review by alexandrebouchard — APPROVED** [review]

**Comment by alexandrebouchard** [comment]
Thanks Kevin!

**Comment by kevinchern** [comment]
Woohoo :)

**Pull request merged**
