### PR TITLE
recursive check for build gradle arch

### PR DESCRIPTION
**Pull request by kevinchern**
for https://github.com/UBC-Stat-ML/blangSDK/issues/144

### CODE REVIEW

**Comment by alexandrebouchard** [comment]
Thanks a lot! 
ls options tend to not be super portable, I was wondering if a pure Java version of this patch would be easy to do?

**Comment by kevinchern** [comment]
Oh right that's a good point, I'll give it a try tomorrow if time permits.

**Comment by kevinchern** [comment]
@alexandrebouchard  the latest commit should work https://github.com/UBC-Stat-ML/blangSDK/pull/145/commits/05c337d737da51bae5e2655e27f06faca3b53219

**Comment by alexandrebouchard** [comment]
Looks good thanks!

The fix is great but I thought of some other potential related problems so let's chat this afternoon. 

- what if blang is called say at / - this will get really slow
- what if called in say blangSDK/src, will still run into issues
- in some sense generally it is error prone to ask user to be in a specific directory when running something

Potential idea: move to a more git-like style

- ask user to add --init first time: only if that flag is present then we do the recursive checks
- when init is not there, we just look for .blangcompilation
- optionally, as bonus we could allow the blang command to be ran in any subdirectory of the blang project

This way if user does blang --help we are sure something crazy will not happen, and we also minimize the chances the user calls blang in the wrong folder

I guess we could also just do a special case for "blang --help" the git-style solution will need that anyways..

Let chat soon

**Pull request merged**
