### PR TITLE
Added Multinomial distribution

### PR DESCRIPTION
**Pull request by garyzhubc**

### CODE REVIEW

**Comment by garyzhubc** [comment]
Looks like my addition has made a lot of other tests failed - mostly because of `No kernels produced by model to be tested`. Is this an error due to compilation?

**Comment by alexandrebouchard** [comment]
I think this is because the changes Examples cause a runtime error?

**Comment by garyzhubc** [comment]
I see. I might have forgotten to commit two changes. Let's see if this works now. 

Is pull request the only way I can check my implementation? It seems I don't have access to Travis for this project.

**Comment by alexandrebouchard** [comment]
You can also run the tests using ./gradlew test

**Pull request closed without merging**
